### ISSUE TITLE
Update SensSoft to Flagon

### ISSUE THREAD

**Issue by brucearctor** [apache/flagon-distill#10]
SensSoft still appears in many places througout repos.

Needing to update to remove references to SensSoft, in favor of Flagon.

Ex: https://github.com/apache/incubator-flagon-distill/blob/master/CONTRIBUTING.rst , etc...

**Comment by brucearctor** [comment]
This might be best treated as an epic, and have some distinct issues as some work gets done?  But... however work is best tracked?!?

**Comment by poorejc** [comment]
This was fixed in recent release.
