### ISSUE TITLE
feat(LogMagicMethods): Implement magic methods for log class to allow comparison operators

### ISSUE THREAD

**Issue by rc10house** [apache/flagon-distill#43]
# Problem
We need to be able to compare logs to each other using arithmetic operators (`>,<,==,>=,...`). This is possible by implementing magic methods (or dunder methods, i.e. `__eq__()`, guide [here](https://rszalski.github.io/magicmethods/)). We also need to decide which metric to compare the logs with; most likely we should use timestamp for chronological comparison–but this doesn't exactly make sense for the equals operator (`==`) so we will need to figure out a different metric for that. 

*Note:* timestamp comparison with arithmetic operators becomes possible by default when using PKSUID and comparing on the ID objects. We could go this route by bubbling up the PKSUID comparison magic methods to the Log object itself. This would also allow us to redefine the ‘==’ comparator method to something other than timestamp if we want to.

# Other notes
- `raw` logs have a single time stamp 
- `interval` logs have a start and stop time stamp 
- We can compare two logs using comparison operators to see if one occurred before or after another 
- `Log1 > Log2` iff Log1 min time strictly greater than Log2 max time 
- `log1 < log2` iff Log1 min time strictly less than Log2 max time 
- `log1 == log2` if Ids are identical (this is one option, in theory they could have different fields though if one of them has been mutated)  
- Need to think through whether this is too overloaded because behavior of operator and the underlying field it's using to compare depends on the operator itself 

# Definition of Done
- Should be comparable with each other 
- Should be able to compare logs against a timestamp 
    - `Log1 < datetime.now()` 
- Should be able to check if logs fall within a given interval: 
    - `datetime.datetime(year=2018, month=3, day=20) < log1 < datetime.datetime(year=2018, month=6, day=21)` 
- If you add two or more logs, the resulting object should be a chronologically-ordered segment 
- Should support [string magic methods](https://www.geeksforgeeks.org/dunder-magic-methods-python/)

**Comment by jlhitzeman** [comment]
Assign
